id = "redscript"
name = "REDscript"
version = "0.1.0"
schema_version = 1
authors = ["jekky <gh@jekky.dev>"]
description = """
REDscript is an open-source programming language and toolset designed to work natively with Cyberpunk 2077's scripting runtime.
"""
repository = "https://github.com/jac3km4/redscript-zed"

[language_servers.redscript-ide]
name = "redscript-ide"
language = "REDscript"

[grammars.redscript]
repository = "https://github.com/jac3km4/tree-sitter-redscript"
rev = "d2037518873b1a7e1b83c96063cd71f89b3d0edf"
